package com.frezzamusic.app
import android.content.*;import android.net.Uri;import android.os.Bundle
import androidx.activity.ComponentActivity;import androidx.activity.compose.setContent;import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.lazy.*;import androidx.compose.material.icons.Icons;import androidx.compose.material.icons.filled.*;import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.*;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.unit.dp
import androidx.media3.common.Player
import com.frezzamusic.app.data.*;import com.frezzamusic.app.model.*;import com.frezzamusic.app.player.*;import com.frezzamusic.app.ui.theme.FrezzaTheme
import kotlinx.coroutines.Dispatchers;import kotlinx.coroutines.withContext
class MainActivity:ComponentActivity(){private lateinit var folders:FolderMusicRepository;private var added:(()->Unit)?=null;private val picker=registerForActivityResult(ActivityResultContracts.OpenDocumentTree()){u->u?:return@registerForActivityResult;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};folders.add(u);added?.invoke()};override fun onCreate(b:Bundle?){super.onCreate(b);folders=FolderMusicRepository(this);setContent{FrezzaTheme{App(folders,{cb->added=cb;picker.launch(null)})}}}}
enum class Tab{HOME,LIBRARY,ONLINE,PLAYLISTS,MORE}
@Composable fun App(repo:FolderMusicRepository,pick:((()->Unit))->Unit){val ctx=androidx.compose.ui.platform.LocalContext.current;val user=remember{UserLibraryRepository(ctx)};val pc=remember{PlaybackController(ctx,DevelopmentDriveStreamResolver(),user)};var tick by remember{mutableIntStateOf(0)};DisposableEffect(Unit){pc.onChanged={tick++};pc.connect();onDispose{pc.release()}};var tab by remember{mutableStateOf(Tab.HOME)};var local by remember{mutableStateOf(emptyList<Track>())};var artists by remember{mutableStateOf(emptyList<Artist>())};var roots by remember{mutableStateOf(repo.folders())};var selectedAlbum by remember{mutableStateOf<Album?>(null)};var query by remember{mutableStateOf("")};var loading by remember{mutableStateOf(false)}
 suspend fun refresh(){loading=true;roots=repo.folders();local=withContext(Dispatchers.IO){repo.scan()};artists=FrezzaDriveCatalog().artists();loading=false}
 LaunchedEffect(Unit){refresh()};val remote=artists.flatMap{it.albums}.flatMap{it.tracks};val all=local+remote;val c=pc.controller;val current=all.find{it.id==c?.currentMediaItem?.mediaId};Scaffold(bottomBar={Column{Mini(current,c?.isPlaying==true,{pc.toggle()},{tab=Tab.HOME});NavigationBar{listOf(Tab.HOME to Icons.Default.Home,Tab.LIBRARY to Icons.Default.LibraryMusic,Tab.ONLINE to Icons.Default.Cloud,Tab.PLAYLISTS to Icons.Default.PlaylistPlay,Tab.MORE to Icons.Default.MoreHoriz).forEach{(t,i)->NavigationBarItem(selected=tab==t,onClick={tab=t;selectedAlbum=null},icon={Icon(i,null)},label={Text(t.name.lowercase().replaceFirstChar{it.uppercase()})})}}}}){pad->Box(Modifier.padding(pad)){when(tab){
 Tab.HOME->Home(local,remote,user,all,{t->pc.play(t,all)},{tab=Tab.ONLINE})
 Tab.LIBRARY->Library(local,query,{query=it},{t->pc.play(t,local)},user)
 Tab.ONLINE->Online(artists,selectedAlbum,{selectedAlbum=it},{selectedAlbum=null},{t,a->pc.play(t,a.tracks)},user)
 Tab.PLAYLISTS->Collections(user,all,{t,q->pc.play(t,q)})
 Tab.MORE->More(roots,{pick{tick++}},{repo.remove(it);tick++},{tab=Tab.LIBRARY})
 };if(loading)LinearProgressIndicator(Modifier.fillMaxWidth())};LaunchedEffect(tick){if(tick>0&&roots!=repo.folders())refresh()}}
}
@Composable fun Home(local:List<Track>,remote:List<Track>,u:UserLibraryRepository,all:List<Track>,play:(Track)->Unit,online:()->Unit){val fav=u.favorites();LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("FREZZAMUSIC",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text("${local.size} locais • ${remote.size} online • ${fav.size} favoritas")};item{Button(onClick=online){Icon(Icons.Default.Cloud,null);Spacer(Modifier.width(8.dp));Text("Abrir FREZZAMUSIC Online")}};item{Text("Recentes",fontWeight=FontWeight.Bold)};items(u.history().mapNotNull{h->all.find{it.id==h.trackId}}.take(12)){RowTrack(it,fav.contains(it.id),{play(it)},{u.toggleFavorite(it.id)})}}}
@Composable fun Library(ts:List<Track>,q:String,setQ:(String)->Unit,play:(Track)->Unit,u:UserLibraryRepository){var mode by remember{mutableStateOf("Músicas")};val f=ts.filter{q.isBlank()||listOf(it.title,it.artist,it.album,it.genre?:"").any{x->x.contains(q,true)}};Column{OutlinedTextField(q,setQ,Modifier.fillMaxWidth().padding(12.dp),label={Text("Buscar biblioteca")},leadingIcon={Icon(Icons.Default.Search,null)});ScrollableTabRow(listOf("Músicas","Artistas","Álbuns","Gêneros","Pastas").indexOf(mode)){listOf("Músicas","Artistas","Álbuns","Gêneros","Pastas").forEachIndexed{i,x->Tab(i==listOf("Músicas","Artistas","Álbuns","Gêneros","Pastas").indexOf(mode),{mode=x},{Text(x)})}};LazyColumn{when(mode){"Músicas"->items(f){RowTrack(it,u.favorites().contains(it.id),{play(it)},{u.toggleFavorite(it.id)})};"Artistas"->items(f.groupBy{it.artist}.toList()){(n,x)->ListItem(headlineContent={Text(n)},supportingContent={Text("${x.size} faixas")},leadingContent={Icon(Icons.Default.Person,null)})};"Álbuns"->items(f.groupBy{it.album}.toList()){(n,x)->ListItem(headlineContent={Text(n)},supportingContent={Text("${x.first().artist} • ${x.size} faixas")},leadingContent={Icon(Icons.Default.Album,null)})};"Gêneros"->items(f.groupBy{it.genre?:"Sem gênero"}.toList()){(n,x)->ListItem(headlineContent={Text(n)},supportingContent={Text("${x.size} faixas")})};else->item{Text("As pastas autorizadas são administradas em Mais → Pastas.",Modifier.padding(20.dp))}}}}}
@Composable fun Online(as_:List<Artist>,album:Album?,open:(Album)->Unit,back:()->Unit,play:(Track,Album)->Unit,u:UserLibraryRepository){LazyColumn(contentPadding=PaddingValues(16.dp)){if(album!=null){item{TextButton(onClick=back){Icon(Icons.Default.ArrowBack,null);Text("Álbuns")};Text(album.title,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(album.artist)};items(album.tracks){RowTrack(it,u.favorites().contains(it.id),{play(it,album)},{u.toggleFavorite(it.id)})}}else{item{Text("FREZZAMUSIC Online",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Streaming • catálogo remoto")};as_.forEach{a->item{Text(a.name,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=18.dp))};items(a.albums){al->ListItem(Modifier.clickable{open(al)},headlineContent={Text(al.title)},supportingContent={Text("${al.tracks.size} faixas")},leadingContent={Icon(Icons.Default.Album,null)},trailingContent={Icon(Icons.Default.ChevronRight,null)})}}}}}
@Composable fun Collections(u:UserLibraryRepository,all:List<Track>,play:(Track,List<Track>)->Unit){var name by remember{mutableStateOf("")};LazyColumn(contentPadding=PaddingValues(16.dp)){item{Text("Playlists e filas",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Row{OutlinedTextField(name,{name=it},Modifier.weight(1f),label={Text("Nova playlist")});IconButton({if(name.isNotBlank()){u.savePlaylist(UserPlaylist(System.currentTimeMillis().toString(),name));name=""}}){Icon(Icons.Default.Add,null)}}};items(u.playlists()){p->val tracks=p.trackIds.mapNotNull{id->all.find{it.id==id}};ListItem(headlineContent={Text(p.name)},supportingContent={Text("${tracks.size} faixas")},leadingContent={Icon(Icons.Default.PlaylistPlay,null)},trailingContent={IconButton({u.deletePlaylist(p.id)}){Icon(Icons.Default.Delete,null)}})};item{Text("Filas salvas",fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=16.dp))};items(u.queues()){q->ListItem(headlineContent={Text(q.name)},supportingContent={Text("${q.trackIds.size} faixas")},leadingContent={Icon(Icons.Default.QueueMusic,null)})}}}
@Composable fun More(fs:List<Uri>,add:()->Unit,remove:(Uri)->Unit,lib:()->Unit){LazyColumn(contentPadding=PaddingValues(16.dp)){item{Text("Configurações",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Pastas da biblioteca",fontWeight=FontWeight.Bold);Button(onClick=add){Text("Adicionar pasta")}};items(fs){u->ListItem(headlineContent={Text(u.lastPathSegment?:"Pasta")},supportingContent={Text(u.toString(),maxLines=1)},leadingContent={Icon(Icons.Default.Folder,null)},trailingContent={IconButton({remove(u)}){Icon(Icons.Default.Delete,null)}})};item{HorizontalDivider();ListItem(headlineContent={Text("Letras e LRC")},supportingContent={Text("Estrutura preparada para letras embutidas/arquivos sincronizados")},leadingContent={Icon(Icons.Default.Lyrics,null)});ListItem(headlineContent={Text("Áudio")},supportingContent={Text("Media3 • gapless quando suportado • velocidade e crossfade configuráveis na camada de player")},leadingContent={Icon(Icons.Default.Equalizer,null)});ListItem(headlineContent={Text("HQ")},supportingContent={Text("ONLINE_HQ exige autorização futura do backend; não há bypass local")},leadingContent={Icon(Icons.Default.Lock,null)})}}}
@Composable fun RowTrack(t:Track,fav:Boolean,play:()->Unit,toggle:()->Unit){ListItem(Modifier.clickable(onClick=play),headlineContent={Text(t.title)},supportingContent={Text("${t.artist} • ${t.album}")},leadingContent={Icon(if(t.remote)Icons.Default.Cloud else Icons.Default.MusicNote,null)},trailingContent={IconButton(toggle){Icon(if(fav)Icons.Default.Favorite else Icons.Default.FavoriteBorder,null)}})}
@Composable fun Mini(t:Track?,playing:Boolean,toggle:()->Unit,expand:()->Unit){Surface(tonalElevation=6.dp,modifier=Modifier.clickable(onClick=expand)){Row(Modifier.fillMaxWidth().height(64.dp).padding(horizontal=14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Album,null,tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(t?.title?:"Nada tocando",maxLines=1,fontWeight=FontWeight.SemiBold);Text(t?.artist?:"Selecione uma faixa",maxLines=1,style=MaterialTheme.typography.bodySmall)};IconButton(toggle,enabled=t!=null){Icon(if(playing)Icons.Default.Pause else Icons.Default.PlayArrow,null)}}}}
